# Site settings
title: "Tech Blog" 
email: "" # 👈 본인 이메일 주소 입력 (선택)
description: >-
  Deep learning and machine learning
github_username: "SaeSimcheon" 
minimal_mistakes_skin: default 
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 
paginate_path: /page:num/
timezone: "Asia/Seoul" 

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name     : "Sanghyuk Lee" 
  avatar   : "/assets/images/bio-photo.jpg" # 👈 나중에 이 경로에 프로필 사진을 넣으시면 됩니다
  bio      : "Researcher at Soongsil University"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/" # 👈 본인 깃허브 프로필 주소 입력

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/" # 👈 본인 깃허브 프로필 주소 입력

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      mathjax: true # 👈 딥러닝 수식(LaTeX) 렌더링을 위해 기본 활성화 완료
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
